# Generated by Django 3.2 on 2021-12-23 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_profile_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nat_type',
            field=models.TextField(default='NAT'),
        ),
        migrations.AddField(
            model_name='profile',
            name='port',
            field=models.IntegerField(default=0),
        ),
    ]
