# Generated by Django 3.2 on 2021-12-29 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20211224_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_ip_correct',
            field=models.BooleanField(default=True),
        ),
    ]
