# Generated by Django 3.2 on 2021-12-29 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_profile_is_ip_correct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_ip_correct',
            new_name='is_ip_and_mac_correct',
        ),
        migrations.AddField(
            model_name='profile',
            name='mac_address',
            field=models.IntegerField(default=0),
        ),
    ]
