# Generated by Django 3.2 on 2021-12-29 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20211229_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='mac_address',
        ),
        migrations.AddField(
            model_name='profile',
            name='useragent',
            field=models.TextField(default='0'),
        ),
    ]
