# Generated by Django 3.2 on 2021-12-29 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20211229_2028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_ip_and_mac_correct',
            new_name='is_ip_correct',
        ),
    ]
