# Generated by Django 3.2 on 2022-01-07 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_auto_20211230_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ice_candidates',
            field=models.TextField(default=0),
        ),
    ]
