# Generated by Django 3.2 on 2022-01-07 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_profile_ice_candidates'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='first_ice',
            field=models.BooleanField(default=False),
        ),
    ]
