# Generated by Django 3.2 on 2022-01-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_alter_profile_first_ice'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ice_candidates_temp',
            field=models.TextField(default=0),
        ),
    ]
